### ISSUE TITLE
1.0 Release

### ISSUE THREAD

**Issue by minkimcello** [minkimcello/landscape3#14]
## TODOs for 1.0 Release

- [x] #15
- [x] #16
- [ ] #27
- [ ] Write short doc to introduce `landscape3` using [techdocs](https://backstage.io/docs/features/techdocs/)
  - Normally when you click on `Docs` it takes you to a document-specific catalog (i.e., it's the same as `Catalog` but only displays documentation (as entities)). We'll update the sidebar link so that it takes us directly to the doc instead of listing out documentation
    - See https://demo.backstage.io/docs?filters%5Buser%5D=all - that's backstage listing out the docs
- [ ] Cleanup unused features/tabs
  - #36 was supposed to be for issue #27 but also takes care of a lot of the cleanup
  - Looking through the app now (in #36 in its current state), I think we should do the followingL
    - See if there's an easy way to remove Support header bar in the catalog
    - Clean up the filter in the catalog (I forget, this might be a configurable option or we may need to fork the component)
       - We don't need `Processing Status`, `Lifecycle`, `Kind` or `Type`
         - People might want to filter by incubating status and or category/subcategory
    - Clean up the catalog table column headers
      - We don't need `System`, `Type`, `Lifecycle`, `Owner`, or `Actions`
        - Again, this might be configurable or we may need to fork out the entire component from upstream
- [ ] Revisit theme - let's re-review https://landscape.cncf.io/ (I think they promoted landscape2.io to landscape.cncf.io) to apply a more rounded theme. The pink text might not do it.
- [ ] Deploy
  - https://aws.amazon.com/fargate/

## Future Features

- Generate members entities
- Create a plugin for blogposts
- Landscape3 contributors stats plugin
- Implement [clotributor](https://github.com/cncf/clotributor)
